# Use root/rodri as user/password credentials
# Este archivo se debe nombrar --->  stack.yml <---
# EJECUTAR CON ESTA LINEA
# docker-compose -f stack.yml up -d
version: '3.8'

services:

  db:
    container_name: server-mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rodri
    volumes:
      - './volumenes/postgres:/var/lib/mysql'
    hostname: server-mysql

  adminer:
    container_name: server-adminer
    image: adminer
    restart: always
    ports:
      - 8081:8080
    hostname: server-adminer

  app:
     image: 'biblioteca'
     build:
       context: .
     container_name: app
     depends_on:
       - db
     environment:
       - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/biblioteca
       - SPRING_DATASOURCE_USERNAME=root
       - SPRING_DATASOURCE_PASSWORD=rodri
       - SPRING_JPA_HIBERNATE_DDL_AUTO=update
     ports:
       - 8082:8080