# Use root/rodri as user/password credentials
# Este archivo se debe nombrar --->  stack.yml <---
# EJECUTAR CON ESTA LINEA
# docker-compose -f stack.yml up -d
version: '3.8'

services:

  db:
    container_name: server-mysql
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rodri
    volumes:
      - './volumenes/postgres:/var/lib/mysql' 
    hostname: server-mysql

  adminer:
    container_name: server-adminer
    image: adminer
    restart: always
    ports:
      - 8081:8080
    hostname: server-adminer